name: OPE Container Test

on:
  push:
    branches: 
      - 'container-base-ope'

env:
    REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  Build:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
     
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Build the image
        run: |
          python --version
          make build
        
      - name: Push beta version
        run: |
          REGISTRY=$(cat base/ope_book_registry)
          REGISTRY_USER=$(cat base/ope_book_user)
          echo $REGISTRY $REGISTRY_USER
          docker login $REGISTRY -u $REGISTRY_USER -p $REGISTRY_PASSWORD
          #docker image list
          docker pull quay.io/gaheyrich/ope:beta-base-ope-image
          #docker image list
          make push

      - name: Show Debug info
        run: |
          IMAGE_TAG=$( make show-tag )
          echo "For debugging purposes, here is the image tag:"
          echo "  $IMAGE_TAG"
      
  
  UI-Test:
    runs-on: ubuntu-latest #use the latest ubuntu container image
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        
      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Installing necessary python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Pull beta-version
        run: |
          make pull-beta

      - name: Run JupyterLab inside container
        run: |
          make run-beta &
          sleep 3

      - name: Run RISE extension tests
        run: |
          make -C tests rise-test
      
      - name: Run Screenshots difference tests
        run: |
          make -C tests screenshots-test
  
  Image-Test:
    runs-on: ubuntu-latest #use the latest ubuntu container image
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Pull beta-version
        run: |
          make pull-beta

      - name: Comparing checksum value
        run: |
          make -C tests checksum-test

  # Approval:
  #   needs: [UI-Test, Image-Test]
  #   environment:
  #     name: approval
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: manual approve
  #     run: |
  #         echo "Publication approved"
  
  # Publish:
  #   runs-on: ubuntu-latest #use the latest ubuntu container image
  #   needs: approval
  #   steps:
  #     - name: Checkout the code
  #       uses: actions/checkout@v3

  #     - name: Push to public version
  #       run: |
  #         REGISTRY=$(cat base/ope_book_registry)
  #         REGISTRY_USER=$(cat base/ope_book_user)
  #         docker login $REGISTRY -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  #         make publish
